/* mmws Tweak.x — the Layer-3 device bridge wiring the RE-confirmed hooks to the native
 * RFC-6455 client (mmwsconn / mmws_sm / mmws). Plain ObjC (.x), no ObjC classes; reaches
 * UIKit/WebKit only via runtime messaging (never a linked UIKit symbol) — matches the mmvideo
 * load-gate model. Hooks confirmed firing on the live webclip in tweak/mmws/REFINDINGS.md §3:
 *   - INTERCEPT mmws://  : -[WebAppController webView:shouldStartLoadWithRequest:navigationType:]
 *   - INJECT mmws.js     : -[UIWebViewWebViewDelegate webView:didClearWindowObject:forFrame:]
 *   - DISPATCH native->JS: -[UIWebView stringByEvaluatingJavaScriptFromString:]  */
#import <Foundation/Foundation.h>
#import <substrate.h>
#import <objc/message.h>
#import <objc/runtime.h>
#import <dispatch/dispatch.h>
#import <string.h>
#import <stdlib.h>
#import <stdint.h>
#import <stdio.h>
#import <stdarg.h>
#import "mmwsconn.h"
#import "mmws_js.h"   /* generated by build.sh: static const char * const MMWS_JS = "..."; */

#define MMWS_MAXID 64
static MMWSConn *g_conns[MMWS_MAXID];
static id        g_webview;   /* the UIWebView, retained, for native->JS dispatch */

/* diagnostic log — OFF in production (bridge verified working 2026-07-01). To debug, set
 * MMWS_DEBUG 1 and re-add mmlog(...) calls; writes to /var/mobile/mmws.log (webclip-writable). */
#define MMWS_DEBUG 0
static void mmlog(const char *fmt, ...) {
    if (!MMWS_DEBUG) return;
    static const char *paths[2] = { "/var/mobile/mmws.log", "/tmp/mmws.log" };
    for (int i = 0; i < 2; i++) {
        FILE *f = fopen(paths[i], "a");
        if (f) { va_list ap; va_start(ap, fmt); vfprintf(f, fmt, ap); va_end(ap); fclose(f); }
    }
}

/* ---- native -> JS (main thread; run-loop callbacks already are) --------------------------- */
static id nsstr(const char *s) {
    return ((id (*)(id, SEL, const char *))objc_msgSend)(
        (id)objc_getClass("NSString"), sel_registerName("stringWithUTF8String:"), s);
}
static void eval_on_webview(const char *js) {
    if (!g_webview || !js) return;
    id s = nsstr(js);
    if (s) ((id (*)(id, SEL, id))objc_msgSend)(
        g_webview, sel_registerName("stringByEvaluatingJavaScriptFromString:"), s);
}

/* escape src[0..n) into a single-quoted JS string body.
 * NB: numeric char codes (not '\\' / '\'' literals) — Logos's tokenizer mis-tracks braces
 * around escaped-quote char literals ("fell off the face of the planet"). 0x5C=\  0x27='  */
static size_t js_escape(const uint8_t *src, size_t n, char *dst, size_t cap) {
    size_t o = 0;
    for (size_t i = 0; i < n && o + 6 < cap; i++) {
        uint8_t c = src[i];
        if      (c == 0x5C || c == 0x27) { dst[o++] = 0x5C; dst[o++] = (char)c; }
        else if (c == 0x0A) { dst[o++] = 0x5C; dst[o++] = 'n'; }
        else if (c == 0x0D) { dst[o++] = 0x5C; dst[o++] = 'r'; }
        else if (c == 0x09) { dst[o++] = 0x5C; dst[o++] = 't'; }
        else if (c < 0x20)  { o += (size_t)snprintf(dst + o, cap - o, "\\x%02x", c); }
        else                { dst[o++] = (char)c; }
    }
    dst[o] = 0;
    return o;
}

/* __mmwsDispatch(sid, type[, arg]) — arg is a JS string (message/error) or number (close code) */
static void dispatch_js(int sid, const char *type, const uint8_t *data, size_t n, int code, int hascode) {
    size_t cap = n * 6 + 128;
    char *buf = (char *)malloc(cap);
    if (!buf) return;
    size_t o;
    if (hascode) {
        o = (size_t)snprintf(buf, cap, "if(window.__mmwsDispatch)__mmwsDispatch(%d,'%s',%d)", sid, type, code);
    } else if (data) {
        o = (size_t)snprintf(buf, cap, "if(window.__mmwsDispatch)__mmwsDispatch(%d,'%s','", sid, type);
        o += js_escape(data, n, buf + o, cap - o - 4);
        o += (size_t)snprintf(buf + o, cap - o, "')");
    } else {
        o = (size_t)snprintf(buf, cap, "if(window.__mmwsDispatch)__mmwsDispatch(%d,'%s')", sid, type);
    }
    (void)o;
    eval_on_webview(buf);
    free(buf);
}

/* ---- mmwsconn callbacks (ud carries the JS socket id) ------------------------------------- */
static void cb_open (MMWSConn *c, void *ud) { (void)c; dispatch_js((int)(intptr_t)ud, "open", NULL, 0, 0, 0); }
static void cb_msg  (MMWSConn *c, uint8_t op, const uint8_t *d, size_t n, void *ud) {
    (void)c; (void)op; dispatch_js((int)(intptr_t)ud, "message", d, n, 0, 0);
}
static void cb_close(MMWSConn *c, uint16_t code, void *ud) {
    int sid = (int)(intptr_t)ud;
    dispatch_js(sid, "close", NULL, 0, code, 1);
    if (sid >= 0 && sid < MMWS_MAXID) g_conns[sid] = NULL;
    dispatch_async_f(dispatch_get_main_queue(), c, (dispatch_function_t)mmwsconn_free);  /* defer free */
}
static void cb_error(MMWSConn *c, const char *msg, void *ud) {
    int sid = (int)(intptr_t)ud;
    dispatch_js(sid, "error", (const uint8_t *)(msg ? msg : "error"), msg ? strlen(msg) : 5, 0, 0);
    if (sid >= 0 && sid < MMWS_MAXID) g_conns[sid] = NULL;
    dispatch_async_f(dispatch_get_main_queue(), c, (dispatch_function_t)mmwsconn_free);
}

/* ---- mmws:// URL scheme parsing (JS -> native) ------------------------------------------- */
static int hexv(char c) {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}
static size_t pct_decode(const char *s, size_t n, char *out, size_t cap) {
    size_t o = 0;
    for (size_t i = 0; i < n && o + 1 < cap; i++) {
        if (s[i] == '%' && i + 2 < n) {
            int h = hexv(s[i + 1]), l = hexv(s[i + 2]);
            if (h >= 0 && l >= 0) { out[o++] = (char)(h * 16 + l); i += 2; continue; }
        }
        out[o++] = (s[i] == '+') ? ' ' : s[i];
    }
    out[o] = 0;
    return o;
}

static void handle_mmws(const char *url) {
    if (!url || strncmp(url, "mmws://", 7) != 0) return;
    const char *p = url + 7;
    char op[16]; int oi = 0;
    while (*p && *p != '/' && oi < 15) op[oi++] = *p++;
    op[oi] = 0;
    if (*p == '/') p++;
    int sid = atoi(p);
    while (*p && *p != '?') p++;
    const char *query = (*p == '?') ? p + 1 : "";
    if (sid < 0 || sid >= MMWS_MAXID) return;

    if (strcmp(op, "open") == 0) {
        char wsurl[600]; wsurl[0] = 0;
        const char *u = strstr(query, "url=");
        if (u) { u += 4; const char *e = strchr(u, '&'); size_t len = e ? (size_t)(e - u) : strlen(u);
                 pct_decode(u, len, wsurl, sizeof wsurl); }
        const char *q = wsurl;
        if (strncmp(q, "ws://", 5) == 0) q += 5;
        char host[160]; int hi = 0;
        while (*q && *q != ':' && *q != '/' && hi < 159) host[hi++] = *q++;
        host[hi] = 0;
        int port = 80;
        if (*q == ':') { q++; port = atoi(q); while (*q && *q != '/') q++; }
        const char *path = (*q == '/') ? q : "/";
        mmwsconn_cb cb;
        cb.on_open = cb_open; cb.on_message = cb_msg; cb.on_close = cb_close; cb.on_error = cb_error;
        cb.ud = (void *)(intptr_t)sid;
        MMWSConn *c = mmwsconn_open(host, port, path, &cb);
        g_conns[sid] = c;
        if (!c) dispatch_js(sid, "error", (const uint8_t *)"open failed", 11, 0, 0);
    } else if (strcmp(op, "send") == 0) {
        if (!g_conns[sid]) return;
        const char *d = strstr(query, "d=");
        if (d) { d += 2; const char *e = strchr(d, '&'); size_t len = e ? (size_t)(e - d) : strlen(d);
                 char *buf = (char *)malloc(len + 1); if (!buf) return;
                 size_t dn = pct_decode(d, len, buf, len + 1);
                 mmwsconn_send_text(g_conns[sid], (const uint8_t *)buf, dn);
                 free(buf); }
    } else if (strcmp(op, "close") == 0) {
        if (!g_conns[sid]) return;
        int code = 1000; const char *cc = strstr(query, "c="); if (cc) code = atoi(cc + 2);
        mmwsconn_close(g_conns[sid], (uint16_t)code);
    }
}

/* ---- hooks (RE-confirmed classes) -------------------------------------------------------- */
%hook WebAppController
- (BOOL)webView:(id)wv shouldStartLoadWithRequest:(NSURLRequest *)req navigationType:(int)nt {
    NSURL *u = [req URL];
    NSString *scheme = [u scheme];
    if (scheme && [scheme caseInsensitiveCompare:@"mmws"] == NSOrderedSame) {
        if (!g_webview) g_webview = [wv retain];
        handle_mmws([[u absoluteString] UTF8String]);
        return NO;
    }
    return %orig;
}
%end

%hook UIWebViewWebViewDelegate
- (void)webView:(id)wv didClearWindowObject:(id)win forFrame:(id)frame {
    if (win) {
        id s = nsstr(MMWS_JS);
        if (s) ((id (*)(id, SEL, id))objc_msgSend)(win, sel_registerName("evaluateWebScript:"), s);
    }
    %orig;
}
%end
